#spring:
## 配置数据源信息
#datasource:
## 配置数据源类型
#type: com.zaxxer.hikari.HikariDataSource
## 配置连接数据库信息
#driver-class-name: com.mysql.cj.jdbc.Driver
#url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false
#username: root
#password: 591888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 591888
    drive-class-name: com.mysql.jdbc.Driver